<a href="https://colab.research.google.com/github/surekhaashtagi/PasswordGenerator/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
l=[2,3,4,5,6]
data=np.array(l)
print(data)

[2 3 4 5 6]


In [6]:
l=[[1,2,3],[7,8,9],[4,5,6,]]
a1=np.array(l)
print(a1)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [8]:
s=a1[0:]
print(s)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [9]:
s=a1[1:2]
print(s)

[[7 8 9]]


In [10]:
print(a1[0:2,1:2])


[[2]
 [8]]


In [11]:
print(a1[1,0:2])

[7 8]


In [12]:
shp=np.shape(l)
print(shp)

(3, 3)


In [14]:
rng=np.arange(1,10)
print(rng)

[1 2 3 4 5 6 7 8 9]


In [21]:
zer=np.zeros([1,9])
print(zer)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
one=np.ones([1,10])
print(one)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
l=np.array([1,2,3,4,6,7])

print(type(l))

<class 'numpy.ndarray'>


In [25]:
print(l[2])

3


In [28]:
print(l[5])

7


operations on arrays

In [29]:
a=10
b=20
print(a+b)

30


In [30]:
print(a-b)

-10


In [31]:
print(a*b)

200


In [32]:
print(a/b)

0.5


In [33]:
print(a%b)

10


In [34]:
print(a//b)

0


In [35]:
print(a**b)

100000000000000000000


In [43]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [46]:
l=np.array([12,23,34,45,56,67,78,89,90])
print('min values: ',min(l))
print('max values: ',max(l))
print('sum values: ',sum(l))
print('mean values: ',np.mean(l))
print('median values: ',np.median(l))
print('standard values: ',np.std(l))
print('var value: ',np.var(l))


min values:  12
max values:  90
sum values:  494
mean values:  54.888888888888886
median values:  56.0
standard values:  26.80980104549016
var value:  718.7654320987654
